name: DeFiChain Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  jellyfish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: 16

      - name: Upgrade dependencies
        run: |
          npx npm-check-updates -l m -u --deep --target newest --pre -f "/^defichain|@defichain\/.+/" -x "/^@defichain\/(whale|playground)-.+/" \
          | grep -q 'Run npm install to install new versions' && \
          npm i

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: 'build(deps): bump @defichain/jellyfish dependencies'
          commit-message: 'build(deps): bump @defichain/jellyfish dependencies'
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain/jellyfish` dependencies to the latest release.
          branch: defichain-bot/bump-jellyfish-deps

  whale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: 16

      - name: Upgrade dependencies
        run: |
          npx npm-check-updates -l m -u --deep --target newest --pre -f "/^@defichain\/whale-.+/" \
          | grep -q 'Run npm install to install new versions' && \
          npm i

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: 'build(deps): bump @defichain/whale dependencies'
          commit-message: 'build(deps): bump @defichain/whale dependencies'
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain/whale` dependencies to the latest release.
          branch: defichain-bot/bump-whale-deps

  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: 16

      - name: Upgrade dependencies
        run: |
          npx npm-check-updates -l m -u --deep --target newest --pre -f "/^@defichain\/playground-.+/" \
          | grep -q 'Run npm install to install new versions' && \
          npm i

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          committer: DeFiChain Bot <github-bot@defichain.com>
          author: DeFiChain Bot <github-bot@defichain.com>
          title: 'build(deps): bump @defichain/playground dependencies'
          commit-message: 'build(deps): bump @defichain/playground dependencies'
          body: |
            #### What kind of PR is this?:
            /kind dependencies
            #### What this PR does / why we need it:
            Bump `@defichain/playground` dependencies to the latest release.
          branch: defichain-bot/bump-playground-deps
